#!/bin/bash
# ATIS encoding script. This script converts the audio files under
# the ./audio directory to C++ variables.
# Copyright (C) 2023 PixelSergey
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

if [ -z "$1" ]
then
    DIR="female"
else
    DIR=$1
fi

if [ ! -d "./audio/$DIR" ]
then
    echo "Voice pack \"$DIR\" does not exist"
    exit
fi

echo "Encoding $DIR voice pack..."
rm ./atis/audio.h
cd ./audio/$DIR

echo "/**
 * ATIS audio data file. Automatically generated by \`encode.sh\`.
 * Copyright (C) 2023 PixelSergey
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
" > ../../atis/audio.h

for f in *.mp3;
do
    xxd -i $f | sed "s/unsigned char \(.*\) = {/const unsigned char \1 PROGMEM = {/" - | sed "s/unsigned int/const unsigned int/" - >> ../../atis/audio.h
done

echo "Done!"
