/**
 * ATIS audio player header file.
 * Copyright (C) 2023-2024 PixelSergey
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef ATIS_PLAYER
#define ATIS_PLAYER

#include "AudioFileSourcePROGMEM.h"
#include "AudioGeneratorMP3.h"
#include "AudioOutputI2SNoDAC.h"
#undef stack

#include "helper.h"

/**
 * @brief Plays a single MP3 audio clip from program memory.
 * Suitable data is generated by `encode.sh` and written to `audio.h`.
 * 
 * @param[in] data A pointer to the audio data in MP3 format
 * @param[in] length The length of the data array
 */
void playMp3(const unsigned char* data, unsigned int length);

/**
 * @brief Plays the sound file of an individual token of speech.
 * All available token names can be found in the TokenType enum in `helper.h`.
 * 
 * @param[in] token The token to play
 */
void playToken(TokenType token);

#endif